# Form implementation generated from reading ui file '..\ui\admin_dashboard.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import os,sys

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1186, 753)
        MainWindow.setStyleSheet("background-color:rgb(245, 250, 254)")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.icon_only_widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.icon_only_widget.setStyleSheet("QWidget{\n"
"background-color:rgb(31, 149, 239)\n"
"\n"
"\n"
"\n"
"}\n"
"QPushButton{\n"
"color:white;\n"
"height:30px;\n"
"border:none;\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:checked{\n"
"background-color:#f5fafe;\n"
"color:#1f95ef;\n"
"font-weight:bold;\n"
"}\n"
"")
        self.icon_only_widget.setObjectName("icon_only_widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.icon_only_widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(parent=self.icon_only_widget)
        self.label.setMinimumSize(QtCore.QSize(40, 40))
        self.label.setMaximumSize(QtCore.QSize(40, 40))
        self.label.setText("")
        # self.label.setPixmap(QtGui.QPixmap(":/icons/image (1).png"))
        # self.label.setPixmap(QtGui.QPixmap(self.resource_path("assets/icons/iamge (1).png")))
        self.label.setPixmap(QtGui.QPixmap(self.resource_path("assets/icons/image (1).png")))

        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 15, -1, -1)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.project_btn_1 = QtWidgets.QPushButton(parent=self.icon_only_widget)
        self.project_btn_1.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.project_btn_1.setText("")
        icon = QtGui.QIcon()
        # icon.addPixmap(QtGui.QPixmap(":/icons/dashboard_white.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        # icon.addPixmap(QtGui.QPixmap(":/icons/dashboard.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        icon.addPixmap(QtGui.QPixmap(self.resource_path("assets/icons/dashboard_white.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon.addPixmap(QtGui.QPixmap(self.resource_path("assets/icons/dashboard.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.project_btn_1.setIcon(icon)
        self.project_btn_1.setCheckable(True)
        self.project_btn_1.setAutoExclusive(True)
        self.project_btn_1.setObjectName("project_btn_1")
        self.verticalLayout.addWidget(self.project_btn_1)
        self.assignment_btn_1 = QtWidgets.QPushButton(parent=self.icon_only_widget)
        self.assignment_btn_1.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.assignment_btn_1.setText("")
        icon1 = QtGui.QIcon()
        # icon1.addPixmap(QtGui.QPixmap(":/icons/profile_white.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        # icon1.addPixmap(QtGui.QPixmap(":/icons/profile.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        
        icon1.addPixmap(QtGui.QPixmap(self.resource_path("assets/icons/profile_white.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon1.addPixmap(QtGui.QPixmap(self.resource_path("assets/icons/profile.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.assignment_btn_1.setIcon(icon1)
        self.assignment_btn_1.setCheckable(True)
        self.assignment_btn_1.setAutoExclusive(True)
        self.assignment_btn_1.setObjectName("assignment_btn_1")
        self.verticalLayout.addWidget(self.assignment_btn_1)
        self.timesheet_btn_1 = QtWidgets.QPushButton(parent=self.icon_only_widget)
        self.timesheet_btn_1.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.timesheet_btn_1.setText("")
        icon2 = QtGui.QIcon()
        # icon2.addPixmap(QtGui.QPixmap(":/icons/messages_white.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        # icon2.addPixmap(QtGui.QPixmap(":/icons/messages.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        icon2.addPixmap(QtGui.QPixmap(self.resource_path("assets/icons/messages_white.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon2.addPixmap(QtGui.QPixmap(self.resource_path("assets/icons/messages.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.timesheet_btn_1.setIcon(icon2)
        self.timesheet_btn_1.setCheckable(True)
        self.timesheet_btn_1.setAutoExclusive(True)
        self.timesheet_btn_1.setObjectName("timesheet_btn_1")
        self.verticalLayout.addWidget(self.timesheet_btn_1)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 348, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.sign_out_btn_1 = QtWidgets.QPushButton(parent=self.icon_only_widget)
        self.sign_out_btn_1.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.sign_out_btn_1.setText("")
        icon3 = QtGui.QIcon()
        # icon3.addPixmap(QtGui.QPixmap(":/icons/log_out_white.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        # icon3.addPixmap(QtGui.QPixmap(":/icons/log_out.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        icon3.addPixmap(QtGui.QPixmap(self.resource_path("assets/icons/log_out_white.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon3.addPixmap(QtGui.QPixmap(self.resource_path("assets/icons/log_out.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.sign_out_btn_1.setIcon(icon3)
        self.sign_out_btn_1.setCheckable(True)
        self.sign_out_btn_1.setAutoExclusive(False)
        self.sign_out_btn_1.setObjectName("sign_out_btn_1")
        self.verticalLayout_3.addWidget(self.sign_out_btn_1)
        self.gridLayout.addWidget(self.icon_only_widget, 0, 0, 1, 1)
        self.icon_name_widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.icon_name_widget.setStyleSheet("QWidget{\n"
"background-color:rgb(31, 149, 239);\n"
"color:white;\n"
"\n"
"\n"
"\n"
"}\n"
"QPushButton{\n"
"color:white;\n"
"text-align:left;\n"
"height:30px;\n"
"border:none;\n"
"padding-left:10px;\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"background-color:#f5fafe;\n"
"color:#1f95ef;\n"
"font-weight:bold;\n"
"}\n"
"")
        self.icon_name_widget.setObjectName("icon_name_widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.icon_name_widget)
        self.verticalLayout_4.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, 20, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.icon_name_widget)
        self.label_2.setMinimumSize(QtCore.QSize(40, 40))
        self.label_2.setMaximumSize(QtCore.QSize(40, 40))
        self.label_2.setText("")
        # self.label_2.setPixmap(QtGui.QPixmap(":/icons/image (1).png"))
        self.label_2.setPixmap(QtGui.QPixmap(self.resource_path("assets/icons/image (1).png")))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=self.icon_name_widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, 15, -1, -1)
        self.verticalLayout_2.setSpacing(15)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.project_btn_2 = QtWidgets.QPushButton(parent=self.icon_name_widget)
        self.project_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.project_btn_2.setIcon(icon)
        self.project_btn_2.setCheckable(True)
        self.project_btn_2.setAutoExclusive(True)
        self.project_btn_2.setObjectName("project_btn_2")
        self.verticalLayout_2.addWidget(self.project_btn_2)
        self.assignment_btn_2 = QtWidgets.QPushButton(parent=self.icon_name_widget)
        self.assignment_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.assignment_btn_2.setIcon(icon1)
        self.assignment_btn_2.setCheckable(True)
        self.assignment_btn_2.setAutoExclusive(True)
        self.assignment_btn_2.setObjectName("assignment_btn_2")
        self.verticalLayout_2.addWidget(self.assignment_btn_2)
        self.timesheet_btn_2 = QtWidgets.QPushButton(parent=self.icon_name_widget)
        self.timesheet_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.timesheet_btn_2.setIcon(icon2)
        self.timesheet_btn_2.setCheckable(True)
        self.timesheet_btn_2.setAutoExclusive(True)
        self.timesheet_btn_2.setObjectName("timesheet_btn_2")
        self.verticalLayout_2.addWidget(self.timesheet_btn_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 348, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.sign_out_btn_2 = QtWidgets.QPushButton(parent=self.icon_name_widget)
        self.sign_out_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.sign_out_btn_2.setCheckable(True)
        self.sign_out_btn_2.setObjectName("sign_out_btn_2")
        self.verticalLayout_4.addWidget(self.sign_out_btn_2)
        self.gridLayout.addWidget(self.icon_name_widget, 0, 1, 1, 1)
        self.main_menu = QtWidgets.QWidget(parent=self.centralwidget)
        self.main_menu.setObjectName("main_menu")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.main_menu)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.header_widget = QtWidgets.QWidget(parent=self.main_menu)
        self.header_widget.setObjectName("header_widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.header_widget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.menu_btn = QtWidgets.QPushButton(parent=self.header_widget)
        self.menu_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.menu_btn.setStyleSheet("border:none;")
        self.menu_btn.setText("")
        icon4 = QtGui.QIcon()
        # icon4.addPixmap(QtGui.QPixmap(":/icons/menu.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon4.addPixmap(QtGui.QPixmap(self.resource_path("assets/icons/menu.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.menu_btn.setIcon(icon4)
        self.menu_btn.setIconSize(QtCore.QSize(20, 20))
        self.menu_btn.setCheckable(True)
        self.menu_btn.setObjectName("menu_btn")
        self.horizontalLayout_4.addWidget(self.menu_btn)
        spacerItem2 = QtWidgets.QSpacerItem(256, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.search_line_edit = QtWidgets.QLineEdit(parent=self.header_widget)
        self.search_line_edit.setObjectName("search_line_edit")
        self.horizontalLayout.addWidget(self.search_line_edit)
        self.search_btn = QtWidgets.QPushButton(parent=self.header_widget)
        self.search_btn.setStyleSheet("border:none;")
        self.search_btn.setText("")
        icon5 = QtGui.QIcon()
        # icon5.addPixmap(QtGui.QPixmap(":/icons/search.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon5.addPixmap(QtGui.QPixmap(self.resource_path("assets/icons/search.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.search_btn.setIcon(icon5)
        self.search_btn.setIconSize(QtCore.QSize(20, 20))
        self.search_btn.setObjectName("search_btn")
        self.horizontalLayout.addWidget(self.search_btn)
        self.horizontalLayout_4.addLayout(self.horizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(264, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.user_btn = QtWidgets.QPushButton(parent=self.header_widget)
        self.user_btn.setStyleSheet("border:none")
        self.user_btn.setText("")
        icon6 = QtGui.QIcon()
        # icon6.addPixmap(QtGui.QPixmap(":/icons/image (1).png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon6.addPixmap(QtGui.QPixmap(self.resource_path("assets/icons/image (1).png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.user_btn.setIcon(icon6)
        self.user_btn.setIconSize(QtCore.QSize(20, 20))
        self.user_btn.setObjectName("user_btn")
        self.horizontalLayout_4.addWidget(self.user_btn)
        self.verticalLayout_5.addWidget(self.header_widget)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.main_menu)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setStyleSheet("background-color:rgb(255, 255, 255);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.project_page = QtWidgets.QWidget()
        self.project_page.setObjectName("project_page")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.project_page)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.project_page_widget = QtWidgets.QWidget(parent=self.project_page)
        self.project_page_widget.setStyleSheet("")
        self.project_page_widget.setObjectName("project_page_widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.project_page_widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem4 = QtWidgets.QSpacerItem(558, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.subtask_edit_btn = QtWidgets.QPushButton(parent=self.project_page_widget)
        self.subtask_edit_btn.setMinimumSize(QtCore.QSize(20, 20))
        self.subtask_edit_btn.setMaximumSize(QtCore.QSize(20, 20))
        self.subtask_edit_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.subtask_edit_btn.setStyleSheet("border:none;")
        self.subtask_edit_btn.setText("")
        icon7 = QtGui.QIcon()
        # icon7.addPixmap(QtGui.QPixmap(":/icons/edit2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon7.addPixmap(QtGui.QPixmap(self.resource_path("assets/icons/edit2.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.subtask_edit_btn.setIcon(icon7)
        self.subtask_edit_btn.setCheckable(True)
        self.subtask_edit_btn.setObjectName("subtask_edit_btn")
        self.horizontalLayout_5.addWidget(self.subtask_edit_btn)
        self.subtask_delete_btn = QtWidgets.QPushButton(parent=self.project_page_widget)
        self.subtask_delete_btn.setMinimumSize(QtCore.QSize(20, 20))
        self.subtask_delete_btn.setMaximumSize(QtCore.QSize(20, 20))
        self.subtask_delete_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.subtask_delete_btn.setStyleSheet("border:none")
        self.subtask_delete_btn.setText("")
        icon8 = QtGui.QIcon()
        # icon8.addPixmap(QtGui.QPixmap(":/icons/delete2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon8.addPixmap(QtGui.QPixmap(self.resource_path("assets/icons/delete2.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.subtask_delete_btn.setIcon(icon8)
        self.subtask_delete_btn.setCheckable(True)
        self.subtask_delete_btn.setObjectName("subtask_delete_btn")
        self.horizontalLayout_5.addWidget(self.subtask_delete_btn)
        self.add_subtask_btn = QtWidgets.QPushButton(parent=self.project_page_widget)
        self.add_subtask_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.add_subtask_btn.setStyleSheet("QPushButton{\n"
"border:none;\n"
"border-radius:4px;\n"
"padding:6px;\n"
"padding-left-10px;\n"
"padding-right:10px;\n"
"background-color: rgb(31, 149, 239);\n"
"color:white;\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#1668a7;\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"}")
        self.add_subtask_btn.setCheckable(True)
        self.add_subtask_btn.setObjectName("add_subtask_btn")
        self.horizontalLayout_5.addWidget(self.add_subtask_btn)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.subtask_table = QtWidgets.QTableWidget(parent=self.project_page_widget)
        self.subtask_table.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.subtask_table.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.subtask_table.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.subtask_table.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.subtask_table.setAlternatingRowColors(True)
        self.subtask_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.subtask_table.setTextElideMode(QtCore.Qt.TextElideMode.ElideMiddle)
        self.subtask_table.setShowGrid(False)
        self.subtask_table.setObjectName("subtask_table")
        self.subtask_table.setColumnCount(5)
        self.subtask_table.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.subtask_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.subtask_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.subtask_table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.subtask_table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.subtask_table.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.subtask_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.subtask_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.subtask_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.subtask_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.subtask_table.setHorizontalHeaderItem(4, item)
        self.subtask_table.verticalHeader().setVisible(False)
        self.verticalLayout_6.addWidget(self.subtask_table)
        self.gridLayout_2.addLayout(self.verticalLayout_6, 1, 0, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(4)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem5 = QtWidgets.QSpacerItem(558, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.project_edit_btn = QtWidgets.QPushButton(parent=self.project_page_widget)
        self.project_edit_btn.setMinimumSize(QtCore.QSize(20, 20))
        self.project_edit_btn.setMaximumSize(QtCore.QSize(20, 20))
        self.project_edit_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.project_edit_btn.setStyleSheet("border:none;\n"
"")
        self.project_edit_btn.setText("")
        self.project_edit_btn.setIcon(icon7)
        self.project_edit_btn.setIconSize(QtCore.QSize(16, 16))
        self.project_edit_btn.setCheckable(True)
        self.project_edit_btn.setObjectName("project_edit_btn")
        self.horizontalLayout_6.addWidget(self.project_edit_btn)
        self.project_delete_btn = QtWidgets.QPushButton(parent=self.project_page_widget)
        self.project_delete_btn.setMinimumSize(QtCore.QSize(20, 20))
        self.project_delete_btn.setMaximumSize(QtCore.QSize(16, 40))
        self.project_delete_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.project_delete_btn.setStyleSheet("border:none;\n"
"")
        self.project_delete_btn.setText("")
        self.project_delete_btn.setIcon(icon8)
        self.project_delete_btn.setIconSize(QtCore.QSize(16, 16))
        self.project_delete_btn.setCheckable(True)
        self.project_delete_btn.setObjectName("project_delete_btn")
        self.horizontalLayout_6.addWidget(self.project_delete_btn)
        self.new_project_btn = QtWidgets.QPushButton(parent=self.project_page_widget)
        self.new_project_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.new_project_btn.setStyleSheet("QPushButton{\n"
"border:none;\n"
"border-radius:4px;\n"
"padding:6px;\n"
"padding-left-10px;\n"
"padding-right:10px;\n"
"background-color: rgb(31, 149, 239);\n"
"color:white;\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#1668a7;\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"}")
        self.new_project_btn.setCheckable(True)
        self.new_project_btn.setObjectName("new_project_btn")
        self.horizontalLayout_6.addWidget(self.new_project_btn)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.project_table = QtWidgets.QTableWidget(parent=self.project_page_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.project_table.sizePolicy().hasHeightForWidth())
        self.project_table.setSizePolicy(sizePolicy)
        self.project_table.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.project_table.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.project_table.setLineWidth(-1)
        self.project_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.project_table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.project_table.setAutoScrollMargin(16)
        self.project_table.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.EditKeyPressed)
        self.project_table.setAlternatingRowColors(True)
        self.project_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.project_table.setTextElideMode(QtCore.Qt.TextElideMode.ElideLeft)
        self.project_table.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollMode.ScrollPerPixel)
        self.project_table.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollMode.ScrollPerPixel)
        self.project_table.setShowGrid(False)
        self.project_table.setObjectName("project_table")
        self.project_table.setColumnCount(4)
        self.project_table.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.project_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.project_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.project_table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.project_table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.project_table.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.project_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.project_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.project_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.project_table.setHorizontalHeaderItem(3, item)
        self.project_table.horizontalHeader().setVisible(True)
        self.project_table.horizontalHeader().setHighlightSections(True)
        self.project_table.verticalHeader().setVisible(False)
        self.project_table.verticalHeader().setHighlightSections(True)
        self.project_table.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_7.addWidget(self.project_table)
        self.gridLayout_2.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.project_page_widget, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.project_page)
        self.assignment_page = QtWidgets.QWidget()
        self.assignment_page.setObjectName("assignment_page")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.assignment_page)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.assignment_page_widget = QtWidgets.QWidget(parent=self.assignment_page)
        self.assignment_page_widget.setStyleSheet("")
        self.assignment_page_widget.setObjectName("assignment_page_widget")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.assignment_page_widget)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem6 = QtWidgets.QSpacerItem(628, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.edit_assign_btn = QtWidgets.QPushButton(parent=self.assignment_page_widget)
        self.edit_assign_btn.setMinimumSize(QtCore.QSize(20, 20))
        self.edit_assign_btn.setMaximumSize(QtCore.QSize(20, 20))
        self.edit_assign_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.edit_assign_btn.setStyleSheet("border:none;")
        self.edit_assign_btn.setText("")
        self.edit_assign_btn.setIcon(icon7)
        self.edit_assign_btn.setIconSize(QtCore.QSize(16, 16))
        self.edit_assign_btn.setCheckable(True)
        self.edit_assign_btn.setObjectName("edit_assign_btn")
        self.horizontalLayout_7.addWidget(self.edit_assign_btn)
        self.delete_assign_btn = QtWidgets.QPushButton(parent=self.assignment_page_widget)
        self.delete_assign_btn.setMinimumSize(QtCore.QSize(20, 20))
        self.delete_assign_btn.setMaximumSize(QtCore.QSize(20, 20))
        self.delete_assign_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.delete_assign_btn.setStyleSheet("border:none;")
        self.delete_assign_btn.setText("")
        self.delete_assign_btn.setIcon(icon8)
        self.delete_assign_btn.setIconSize(QtCore.QSize(16, 16))
        self.delete_assign_btn.setCheckable(True)
        self.delete_assign_btn.setObjectName("delete_assign_btn")
        self.horizontalLayout_7.addWidget(self.delete_assign_btn)
        self.reset_user_password_btn = QtWidgets.QPushButton(parent=self.assignment_page_widget)
        self.reset_user_password_btn.setStyleSheet("QPushButton{\n"
"border:none;\n"
"border-radius:4px;\n"
"padding:6px;\n"
"padding-left-10px;\n"
"padding-right:10px;\n"
"background-color: rgb(31, 149, 239);\n"
"color:white;\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#1668a7;\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"}")
        self.reset_user_password_btn.setObjectName("reset_user_password_btn")
        self.horizontalLayout_7.addWidget(self.reset_user_password_btn)
        self.create_user_btn = QtWidgets.QPushButton(parent=self.assignment_page_widget)
        self.create_user_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.create_user_btn.setStyleSheet("QPushButton{\n"
"border:none;\n"
"border-radius:4px;\n"
"padding:6px;\n"
"padding-left-10px;\n"
"padding-right:10px;\n"
"background-color: rgb(31, 149, 239);\n"
"color:white;\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#1668a7;\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"}")
        self.create_user_btn.setObjectName("create_user_btn")
        self.horizontalLayout_7.addWidget(self.create_user_btn)
        self.logged_in_btn = QtWidgets.QPushButton(parent=self.assignment_page_widget)
        self.logged_in_btn.setStyleSheet("QPushButton{\n"
"border:none;\n"
"border-radius:4px;\n"
"padding:6px;\n"
"padding-left-10px;\n"
"padding-right:10px;\n"
"background-color: rgb(31, 149, 239);\n"
"color:white;\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#1668a7;\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"}")
        self.logged_in_btn.setObjectName("logged_in_btn")
        self.horizontalLayout_7.addWidget(self.logged_in_btn)
        self.assign_project_btn = QtWidgets.QPushButton(parent=self.assignment_page_widget)
        self.assign_project_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.assign_project_btn.setStyleSheet("QPushButton{\n"
"border:none;\n"
"border-radius:4px;\n"
"padding:6px;\n"
"padding-left-10px;\n"
"padding-right:10px;\n"
"background-color: rgb(31, 149, 239);\n"
"color:white;\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#1668a7;\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"}")
        self.assign_project_btn.setCheckable(True)
        self.assign_project_btn.setObjectName("assign_project_btn")
        self.horizontalLayout_7.addWidget(self.assign_project_btn)
        self.verticalLayout_8.addLayout(self.horizontalLayout_7)
        self.assignment_table = QtWidgets.QTableWidget(parent=self.assignment_page_widget)
        self.assignment_table.setTabletTracking(False)
        self.assignment_table.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.assignment_table.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.assignment_table.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.assignment_table.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.assignment_table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.assignment_table.setDragEnabled(True)
        self.assignment_table.setAlternatingRowColors(True)
        self.assignment_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.assignment_table.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollMode.ScrollPerPixel)
        self.assignment_table.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollMode.ScrollPerPixel)
        self.assignment_table.setShowGrid(False)
        self.assignment_table.setGridStyle(QtCore.Qt.PenStyle.SolidLine)
        self.assignment_table.setObjectName("assignment_table")
        self.assignment_table.setColumnCount(8)
        self.assignment_table.setRowCount(7)
        item = QtWidgets.QTableWidgetItem()
        self.assignment_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.assignment_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.assignment_table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.assignment_table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.assignment_table.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.assignment_table.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.assignment_table.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.assignment_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.assignment_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.assignment_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.assignment_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.assignment_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.assignment_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.assignment_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.assignment_table.setHorizontalHeaderItem(7, item)
        self.assignment_table.verticalHeader().setVisible(False)
        self.verticalLayout_8.addWidget(self.assignment_table)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.gridLayout_4.addWidget(self.assignment_page_widget, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.assignment_page)
        self.Timesheet_page = QtWidgets.QWidget()
        self.Timesheet_page.setObjectName("Timesheet_page")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.Timesheet_page)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.timesheet_page_widget = QtWidgets.QWidget(parent=self.Timesheet_page)
        self.timesheet_page_widget.setStyleSheet("QComboBox{\n"
"border:1px solid #ccc;\n"
"padding:4px;\n"
"border-radius: 2px;\n"
"\n"
"\n"
"}\n"
"QComboBox:focus{\n"
"\n"
" border: 1px solid #0078d4;\n"
"            background-color: #fff;\n"
"\n"
"}")
        self.timesheet_page_widget.setObjectName("timesheet_page_widget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.timesheet_page_widget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_4 = QtWidgets.QLabel(parent=self.timesheet_page_widget)
        self.label_4.setMinimumSize(QtCore.QSize(100, 0))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_8.addWidget(self.label_4)
        self.week_combo = QtWidgets.QComboBox(parent=self.timesheet_page_widget)
        self.week_combo.setMinimumSize(QtCore.QSize(160, 0))
        self.week_combo.setObjectName("week_combo")
        self.horizontalLayout_8.addWidget(self.week_combo)
        self.refresh_btn = QtWidgets.QPushButton(parent=self.timesheet_page_widget)
        self.refresh_btn.setMinimumSize(QtCore.QSize(20, 20))
        self.refresh_btn.setMaximumSize(QtCore.QSize(20, 20))
        self.refresh_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.refresh_btn.setStyleSheet("border:none")
        self.refresh_btn.setText("")
        icon9 = QtGui.QIcon()
        # icon9.addPixmap(QtGui.QPixmap(":/icons/refresh.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon9.addPixmap(QtGui.QPixmap(self.resource_path("assets/icons/refresh.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.refresh_btn.setIcon(icon9)
        self.refresh_btn.setObjectName("refresh_btn")
        self.horizontalLayout_8.addWidget(self.refresh_btn)
        spacerItem7 = QtWidgets.QSpacerItem(368, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem7)
        self.extract_btn = QtWidgets.QPushButton(parent=self.timesheet_page_widget)
        self.extract_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.extract_btn.setStyleSheet("QPushButton{\n"
"border:none;\n"
"border-radius:4px;\n"
"padding:6px;\n"
"padding-left:14px;\n"
"padding-right:14px;\n"
"background-color: rgb(31, 149, 239);\n"
"color:white;\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#1668a7;\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"}")
        self.extract_btn.setObjectName("extract_btn")
        self.horizontalLayout_8.addWidget(self.extract_btn)
        self.gridLayout_6.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        self.timesheet_table = QtWidgets.QTableWidget(parent=self.timesheet_page_widget)
        self.timesheet_table.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.timesheet_table.setLineWidth(1)
        self.timesheet_table.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.timesheet_table.setAlternatingRowColors(True)
        self.timesheet_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.timesheet_table.setShowGrid(False)
        self.timesheet_table.setObjectName("timesheet_table")
        self.timesheet_table.setColumnCount(8)
        self.timesheet_table.setRowCount(8)
        item = QtWidgets.QTableWidgetItem()
        self.timesheet_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.timesheet_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.timesheet_table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.timesheet_table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.timesheet_table.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.timesheet_table.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.timesheet_table.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.timesheet_table.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.timesheet_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.timesheet_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.timesheet_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.timesheet_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.timesheet_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.timesheet_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.timesheet_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.timesheet_table.setHorizontalHeaderItem(7, item)
        self.timesheet_table.verticalHeader().setVisible(False)
        self.gridLayout_6.addWidget(self.timesheet_table, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.timesheet_page_widget, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.Timesheet_page)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.gridLayout.addWidget(self.main_menu, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.project_btn_2.toggled['bool'].connect(self.project_btn_1.setChecked) # type: ignore
        self.assignment_btn_2.toggled['bool'].connect(self.assignment_btn_1.setChecked) # type: ignore
        self.timesheet_btn_1.toggled['bool'].connect(self.timesheet_btn_2.setChecked) # type: ignore
        self.timesheet_btn_2.toggled['bool'].connect(self.timesheet_btn_1.setChecked) # type: ignore
        self.project_btn_1.toggled['bool'].connect(self.project_btn_2.setChecked) # type: ignore
        self.assignment_btn_1.toggled['bool'].connect(self.assignment_btn_2.setChecked) # type: ignore
        self.menu_btn.toggled['bool'].connect(self.icon_only_widget.setHidden) # type: ignore
        self.menu_btn.toggled['bool'].connect(self.icon_name_widget.setVisible) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def resource_path(self,relative_path):
        if getattr(sys, '_MEIPASS', False):
                base_path = sys._MEIPASS
                # print(f"Running in bundled mode. Base path: {base_path}")
        else:
                current_dir=os.path.dirname(os.path.abspath(__file__))
                # base_path = os.path.abspath(os.path.join(current_dir, "..",".."))
                project_root = os.path.abspath(os.path.join(current_dir, "..", ".."))
                base_path = os.path.join(project_root)
                
                # print(f"Running in source mode. Base pat: {base_path}")
        full_path = os.path.join(base_path, relative_path)
        # print(f"Resolved path for {relative_path}: {full_path}")
        return full_path
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "UserName"))
        self.project_btn_2.setText(_translate("MainWindow", "Project"))
        self.assignment_btn_2.setText(_translate("MainWindow", "Assignment"))
        self.timesheet_btn_2.setText(_translate("MainWindow", "TimeSheet"))
        self.sign_out_btn_2.setText(_translate("MainWindow", "Sign out"))
        self.add_subtask_btn.setText(_translate("MainWindow", "Add Subtask"))
        self.subtask_table.setSortingEnabled(True)
        item = self.subtask_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.subtask_table.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.subtask_table.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.subtask_table.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.subtask_table.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.subtask_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Project Id"))
        item = self.subtask_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Project Name"))
        item = self.subtask_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "PSP Element"))
        item = self.subtask_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Subtask"))
        item = self.subtask_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Created Date"))
        self.new_project_btn.setText(_translate("MainWindow", "New Project"))
        self.project_table.setSortingEnabled(True)
        item = self.project_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.project_table.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.project_table.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.project_table.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.project_table.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.project_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Project Id"))
        item = self.project_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Project Name"))
        item = self.project_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "PSP Element"))
        item = self.project_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Created Date"))
        self.reset_user_password_btn.setText(_translate("MainWindow", "Reset User Password"))
        self.create_user_btn.setText(_translate("MainWindow", "Create User"))
        self.logged_in_btn.setText(_translate("MainWindow", "Logged In Users"))
        self.assign_project_btn.setText(_translate("MainWindow", "Assign Project"))
        self.assignment_table.setSortingEnabled(True)
        item = self.assignment_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.assignment_table.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.assignment_table.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.assignment_table.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.assignment_table.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.assignment_table.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.assignment_table.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.assignment_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Assignment Id"))
        item = self.assignment_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Employee Id"))
        item = self.assignment_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Employee Name"))
        item = self.assignment_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Project Name"))
        item = self.assignment_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Subtask"))
        item = self.assignment_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Start Date"))
        item = self.assignment_table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "End Date"))
        item = self.assignment_table.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Duration"))
        self.label_4.setText(_translate("MainWindow", "Select Week"))
        self.extract_btn.setText(_translate("MainWindow", "Extract"))
        item = self.timesheet_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.timesheet_table.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.timesheet_table.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.timesheet_table.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.timesheet_table.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.timesheet_table.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.timesheet_table.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.timesheet_table.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.timesheet_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Sl No."))
        item = self.timesheet_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Week"))
        item = self.timesheet_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Employee Name"))
        item = self.timesheet_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Project"))
        item = self.timesheet_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "PSP"))
        item = self.timesheet_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Segment"))
        item = self.timesheet_table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Subtask"))
        item = self.timesheet_table.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Logged Hours"))
