# Form implementation generated from reading ui file '.\assign_project.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import sys,os


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(333, 339)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(parent=Dialog)
        self.widget.setStyleSheet("QComboBox{\n"
"border:1px solid #ccc;\n"
"padding:4px;\n"
"border-radius: 2px;\n"
"\n"
"\n"
"}\n"
"QComboBox:focus{\n"
"\n"
" border: 1px solid #0078d4;\n"
"            background-color: #fff;\n"
"\n"
"}\n"
"\n"
"QLineEdit{\n"
"color: #666;\n"
"font-size: 14px;\n"
"padding: 4px;\n"
"border: 1px solid #ccc;\n"
"border-radius: 2px;\n"
"background-color: #f9f9f9;\n"
"}\n"
"QLineEdit:focus {\n"
"            border: 1px solid #0078d4;\n"
"            background-color: #fff;\n"
"        }\n"
"")
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.header_widget = QtWidgets.QWidget(parent=self.widget)
        self.header_widget.setStyleSheet("background-color:rgb(31, 149, 239);\n"
"color:white;")
        self.header_widget.setObjectName("header_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.header_widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(96, 10, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(parent=self.header_widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(96, 10, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_3.addWidget(self.header_widget)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem2 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(parent=self.widget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(parent=self.widget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(parent=self.widget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(parent=self.widget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.horizontalLayout_6.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.user_combo = QtWidgets.QComboBox(parent=self.widget)
        self.user_combo.setMinimumSize(QtCore.QSize(170, 0))
        self.user_combo.setObjectName("user_combo")
        self.verticalLayout.addWidget(self.user_combo)
        self.project_combo = QtWidgets.QComboBox(parent=self.widget)
        self.project_combo.setMinimumSize(QtCore.QSize(170, 0))
        self.project_combo.setObjectName("project_combo")
        self.verticalLayout.addWidget(self.project_combo)
        self.subtask_combo = QtWidgets.QComboBox(parent=self.widget)
        self.subtask_combo.setMinimumSize(QtCore.QSize(170, 0))
        self.subtask_combo.setObjectName("subtask_combo")
        self.verticalLayout.addWidget(self.subtask_combo)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.start_date_le = QtWidgets.QLineEdit(parent=self.widget)
        self.start_date_le.setMinimumSize(QtCore.QSize(160, 0))
        self.start_date_le.setObjectName("start_date_le")
        self.horizontalLayout_2.addWidget(self.start_date_le)
        self.start_date_btn = QtWidgets.QPushButton(parent=self.widget)
        self.start_date_btn.setMinimumSize(QtCore.QSize(40, 40))
        self.start_date_btn.setMaximumSize(QtCore.QSize(40, 40))
        self.start_date_btn.setStyleSheet("border:none")
        self.start_date_btn.setText("")
        icon = QtGui.QIcon()
        # icon.addPixmap(QtGui.QPixmap("c:/project management tool/assets/icons/calender.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon.addPixmap(QtGui.QPixmap(self.resource_path("assets/icons/calender.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.start_date_btn.setIcon(icon)
        self.start_date_btn.setIconSize(QtCore.QSize(20, 20))
        self.start_date_btn.setObjectName("start_date_btn")
        self.horizontalLayout_2.addWidget(self.start_date_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.end_date_le = QtWidgets.QLineEdit(parent=self.widget)
        self.end_date_le.setMinimumSize(QtCore.QSize(160, 0))
        self.end_date_le.setObjectName("end_date_le")
        self.horizontalLayout_3.addWidget(self.end_date_le)
        self.end_date_btn = QtWidgets.QPushButton(parent=self.widget)
        self.end_date_btn.setMinimumSize(QtCore.QSize(40, 40))
        self.end_date_btn.setMaximumSize(QtCore.QSize(40, 40))
        self.end_date_btn.setStyleSheet("border:none")
        self.end_date_btn.setText("")
        self.end_date_btn.setIcon(icon)
        self.end_date_btn.setIconSize(QtCore.QSize(20, 20))
        self.end_date_btn.setObjectName("end_date_btn")
        self.horizontalLayout_3.addWidget(self.end_date_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.duration_le = QtWidgets.QLineEdit(parent=self.widget)
        self.duration_le.setMinimumSize(QtCore.QSize(160, 0))
        self.duration_le.setObjectName("duration_le")
        self.horizontalLayout_4.addWidget(self.duration_le)
        spacerItem3 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        spacerItem4 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem5 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.assign_btn = QtWidgets.QPushButton(parent=self.widget)
        self.assign_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.assign_btn.setStyleSheet("QPushButton{\n"
"border:none;\n"
"border-radius:4px;\n"
"background-color:rgb(31, 149, 239);\n"
"color:white;\n"
"padding-right:14px;\n"
"padding-left:14px;\n"
"padding-top:8px;\n"
"padding-bottom:8px;\n"
"\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#1977bf;\n"
"\n"
"\n"
"}")
        self.assign_btn.setCheckable(True)
        self.assign_btn.setObjectName("assign_btn")
        self.horizontalLayout_5.addWidget(self.assign_btn)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_2.setStyleSheet("background-color:#cc0000;padding-right:14px;\n"
"padding-left:14px;\n"
"padding-top:8px;\n"
"padding-bottom:8px;\n"
"border-radius:4px;\n"
"color:#fff;\n"
"border:none;\n"
"border-top-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 255, 255, 255), stop:0.1 rgba(255, 255, 255, 255), stop:0.2 rgba(255, 176, 176, 167), stop:0.3 rgba(255, 151, 151, 92), stop:0.4 rgba(255, 125, 125, 51), stop:0.5 rgba(255, 76, 76, 205), stop:0.52 rgba(255, 76, 76, 205), stop:0.6 rgba(255, 180, 180, 84), stop:1 rgba(255, 255, 255, 0));")
        self.pushButton_2.setCheckable(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_5.addWidget(self.pushButton_2)
        spacerItem6 = QtWidgets.QSpacerItem(128, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.end_date_btn.raise_()
        self.start_date_btn.raise_()
        self.header_widget.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.project_combo.raise_()
        self.subtask_combo.raise_()
        self.start_date_le.raise_()
        self.pushButton_2.raise_()
        self.user_combo.raise_()
        self.duration_le.raise_()
        self.assign_btn.raise_()
        self.label_7.raise_()
        self.duration_le.raise_()
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.pushButton_2.clicked.connect(Dialog.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def resource_path(self,relative_path):
        if getattr(sys, '_MEIPASS', False):
                base_path = sys._MEIPASS
                print(f"Running in bundled mode. Base path: {base_path}")
        else:
                print("hfjdfkdfj")
                current_dir=os.path.dirname(os.path.abspath(__file__))
                # base_path = os.path.abspath(os.path.join(current_dir, "..",".."))
                project_root = os.path.abspath(os.path.join(current_dir, "..", ".."))
                base_path = os.path.join(project_root)
                
                print(f"Running in source mode. Base pat: {base_path}")
        full_path = os.path.join(base_path, relative_path)
        print(f"Resolved path for {relative_path}: {full_path}")
        return full_path
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Assign Project"))
        self.label_2.setText(_translate("Dialog", "Select user"))
        self.label_3.setText(_translate("Dialog", "Select Project"))
        self.label_4.setText(_translate("Dialog", "Select Subtask"))
        self.label_5.setText(_translate("Dialog", "Start Date"))
        self.label_6.setText(_translate("Dialog", "End Date"))
        self.label_7.setText(_translate("Dialog", "Duration"))
        self.assign_btn.setText(_translate("Dialog", "Assign"))
        self.pushButton_2.setText(_translate("Dialog", "Cancel"))
