# Form implementation generated from reading ui file '..\ui\create_project.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(385, 188)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(parent=Dialog)
        self.widget.setStyleSheet("QLineEdit{\n"
"color: #666;\n"
"font-size: 14px;\n"
"padding: 4px;\n"
"border: 1px solid #ccc;\n"
"border-radius: 2px;\n"
"background-color: #f9f9f9;\n"
"}\n"
"QLineEdit:focus {\n"
"            border: 1px solid #0078d4;\n"
"            background-color: #fff;\n"
"        }\n"
"\n"
"QPushButton{\n"
"border:none;\n"
"border-radius:4px;\n"
"background-color:rgb(31, 149, 239);\n"
"color:white;\n"
"padding-right:14px;\n"
"padding-left:14px;\n"
"padding-top:8px;\n"
"padding-bottom:8px;\n"
"\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#1977bf;\n"
"\n"
"\n"
"}")
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.project_name_le = QtWidgets.QLineEdit(parent=self.widget)
        self.project_name_le.setObjectName("project_name_le")
        self.verticalLayout.addWidget(self.project_name_le)
        self.psp_element_le = QtWidgets.QLineEdit(parent=self.widget)
        self.psp_element_le.setObjectName("psp_element_le")
        self.verticalLayout.addWidget(self.psp_element_le)
        self.create_project_btn = QtWidgets.QPushButton(parent=self.widget)
        self.create_project_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.create_project_btn.setCheckable(True)
        self.create_project_btn.setObjectName("create_project_btn")
        self.verticalLayout.addWidget(self.create_project_btn)
        self.gridLayout_2.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Create New Project"))
        self.project_name_le.setPlaceholderText(_translate("Dialog", "Project Name"))
        self.psp_element_le.setPlaceholderText(_translate("Dialog", "PSP Element"))
        self.create_project_btn.setText(_translate("Dialog", "Create"))
