# Form implementation generated from reading ui file '..\ui\create_user.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 348)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(parent=Dialog)
        self.widget.setStyleSheet("QLineEdit{\n"
"color: #666;\n"
"font-size: 14px;\n"
"padding: 4px;\n"
"border: 1px solid #ccc;\n"
"border-radius: 2px;\n"
"background-color: #f9f9f9;\n"
"}\n"
"QLineEdit:focus {\n"
"            border: 1px solid #0078d4;\n"
"            background-color: #fff;\n"
"        }\n"
"\n"
"QComboBox{\n"
"border:1px solid #ccc;\n"
"padding:4px;\n"
"border-radius: 2px;\n"
"\n"
"\n"
"}\n"
"QComboBox:focus{\n"
"\n"
" border: 1px solid #0078d4;\n"
"            background-color: #fff;\n"
"\n"
"}")
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.username_le = QtWidgets.QLineEdit(parent=self.widget)
        self.username_le.setObjectName("username_le")
        self.verticalLayout.addWidget(self.username_le)
        self.employee_id_le = QtWidgets.QLineEdit(parent=self.widget)
        self.employee_id_le.setText("")
        self.employee_id_le.setObjectName("employee_id_le")
        self.verticalLayout.addWidget(self.employee_id_le)
        self.create_pass_le = QtWidgets.QLineEdit(parent=self.widget)
        self.create_pass_le.setObjectName("create_pass_le")
        self.verticalLayout.addWidget(self.create_pass_le)
        self.repeat_pass_le = QtWidgets.QLineEdit(parent=self.widget)
        self.repeat_pass_le.setObjectName("repeat_pass_le")
        self.verticalLayout.addWidget(self.repeat_pass_le)
        self.email_le = QtWidgets.QLineEdit(parent=self.widget)
        self.email_le.setObjectName("email_le")
        self.verticalLayout.addWidget(self.email_le)
        self.reporting_to_combo = QtWidgets.QComboBox(parent=self.widget)
        self.reporting_to_combo.setMinimumSize(QtCore.QSize(0, 30))
        self.reporting_to_combo.setStyleSheet("")
        self.reporting_to_combo.setObjectName("reporting_to_combo")
        self.verticalLayout.addWidget(self.reporting_to_combo)
        self.role_combo = QtWidgets.QComboBox(parent=self.widget)
        self.role_combo.setMinimumSize(QtCore.QSize(0, 30))
        self.role_combo.setStyleSheet("")
        self.role_combo.setObjectName("role_combo")
        self.verticalLayout.addWidget(self.role_combo)
        self.btn_create_user = QtWidgets.QPushButton(parent=self.widget)
        self.btn_create_user.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_create_user.setStyleSheet("QPushButton{\n"
"border:none;\n"
"border-radius:4px;\n"
"padding:7px;\n"
"padding-left-10px;\n"
"padding-right:10px;\n"
"background-color: rgb(31, 149, 239);\n"
"color:white;\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#1668a7;\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"}")
        self.btn_create_user.setObjectName("btn_create_user")
        self.verticalLayout.addWidget(self.btn_create_user)
        self.gridLayout_2.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Create User"))
        self.username_le.setPlaceholderText(_translate("Dialog", "Enter username"))
        self.employee_id_le.setPlaceholderText(_translate("Dialog", "Employee Id"))
        self.create_pass_le.setPlaceholderText(_translate("Dialog", "Create Password"))
        self.repeat_pass_le.setPlaceholderText(_translate("Dialog", "Repeat Password"))
        self.email_le.setPlaceholderText(_translate("Dialog", "User email"))
        self.btn_create_user.setText(_translate("Dialog", "Create User"))
