# Form implementation generated from reading ui file '..\ui\employee_dashboard.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import sys,os

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1205, 701)
        MainWindow.setStyleSheet("background-color: rgb(245, 250, 254);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.icon_only_widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.icon_only_widget.setStyleSheet("QWidget{\n"
"\n"
"    background-color: rgb(31, 149, 239);\n"
"\n"
"}\n"
"QPushButton{\n"
"\n"
"color:white;\n"
"\n"
"height:30px;\n"
"border:none;\n"
"margin-top:15px;\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:checked{\n"
"\n"
"background-color: rgb(245, 250, 254);\n"
"color:#1f95ef;\n"
"font-weight:bold;\n"
"}")
        self.icon_only_widget.setObjectName("icon_only_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.icon_only_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(parent=self.icon_only_widget)
        self.label.setMinimumSize(QtCore.QSize(40, 40))
        self.label.setMaximumSize(QtCore.QSize(40, 40))
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.label.setText("")
        # self.label.setPixmap(QtGui.QPixmap(":/icons/image (1).png"))
        self.label.setPixmap(QtGui.QPixmap(self.resource_path("assets/icons/image (1).png")))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.project_btn_1 = QtWidgets.QPushButton(parent=self.icon_only_widget)
        self.project_btn_1.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.project_btn_1.setText("")
        icon = QtGui.QIcon()
        # icon.addPixmap(QtGui.QPixmap(":/icons/dashboard_white.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        # icon.addPixmap(QtGui.QPixmap(":/icons/dashboard.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        icon.addPixmap(QtGui.QPixmap(self.resource_path("assets/icons/dashboard_white.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon.addPixmap(QtGui.QPixmap(self.resource_path("assets/icons/dashboard.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.project_btn_1.setIcon(icon)
        self.project_btn_1.setIconSize(QtCore.QSize(20, 20))
        self.project_btn_1.setCheckable(True)
        self.project_btn_1.setAutoExclusive(True)
        self.project_btn_1.setObjectName("project_btn_1")
        self.verticalLayout.addWidget(self.project_btn_1)
        self.regularization_btn_1 = QtWidgets.QPushButton(parent=self.icon_only_widget)
        self.regularization_btn_1.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.regularization_btn_1.setText("")
        icon1 = QtGui.QIcon()
        # icon1.addPixmap(QtGui.QPixmap(":/icons/regularization_white.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        # icon1.addPixmap(QtGui.QPixmap(":/icons/regularization.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        icon1.addPixmap(QtGui.QPixmap(self.resource_path("assets/icons/regularization_white.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon1.addPixmap(QtGui.QPixmap(self.resource_path("assets/icons/regularization.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.regularization_btn_1.setIcon(icon1)
        self.regularization_btn_1.setIconSize(QtCore.QSize(20, 20))
        self.regularization_btn_1.setCheckable(True)
        self.regularization_btn_1.setAutoExclusive(True)
        self.regularization_btn_1.setObjectName("regularization_btn_1")
        self.verticalLayout.addWidget(self.regularization_btn_1)
        spacerItem = QtWidgets.QSpacerItem(20, 367, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.sign_out_btn_1 = QtWidgets.QPushButton(parent=self.icon_only_widget)
        self.sign_out_btn_1.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.sign_out_btn_1.setText("")
        icon2 = QtGui.QIcon()
        # icon2.addPixmap(QtGui.QPixmap(":/icons/log_out_white.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        # icon2.addPixmap(QtGui.QPixmap(":/icons/log_out.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        icon2.addPixmap(QtGui.QPixmap(self.resource_path("assets/icons/log_out_white.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon2.addPixmap(QtGui.QPixmap(self.resource_path("assets/icons/log_out.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.sign_out_btn_1.setIcon(icon2)
        self.sign_out_btn_1.setCheckable(True)
        self.sign_out_btn_1.setObjectName("sign_out_btn_1")
        self.verticalLayout.addWidget(self.sign_out_btn_1)
        self.gridLayout.addWidget(self.icon_only_widget, 0, 0, 1, 1)
        self.icon_name_widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.icon_name_widget.setStyleSheet("QWidget{\n"
"\n"
"    background-color: rgb(31, 149, 239);\n"
"color:white;\n"
"\n"
"}\n"
"\n"
"QPushButton{\n"
"\n"
"color:white;\n"
"text-align:left;\n"
"height:30px;\n"
"border:none;\n"
"padding-left:12px;\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"margin-top:15px;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"\n"
"background-color:#f5fafe;\n"
"color:#1f95ef;\n"
"font-weight:bold;\n"
"}")
        self.icon_name_widget.setObjectName("icon_name_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.icon_name_widget)
        self.verticalLayout_2.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, 20, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.icon_name_widget)
        self.label_2.setMinimumSize(QtCore.QSize(40, 40))
        self.label_2.setMaximumSize(QtCore.QSize(40, 40))
        self.label_2.setText("")
        # self.label_2.setPixmap(QtGui.QPixmap(":/icons/image (1).png"))
        self.label_2.setPixmap(QtGui.QPixmap(self.resource_path("assets/icons/image (1).png")))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=self.icon_name_widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.project_btn_2 = QtWidgets.QPushButton(parent=self.icon_name_widget)
        self.project_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.project_btn_2.setIcon(icon)
        self.project_btn_2.setIconSize(QtCore.QSize(20, 20))
        self.project_btn_2.setCheckable(True)
        self.project_btn_2.setAutoExclusive(True)
        self.project_btn_2.setObjectName("project_btn_2")
        self.verticalLayout_2.addWidget(self.project_btn_2)
        self.regularization_btn_2 = QtWidgets.QPushButton(parent=self.icon_name_widget)
        self.regularization_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.regularization_btn_2.setIcon(icon1)
        self.regularization_btn_2.setIconSize(QtCore.QSize(20, 20))
        self.regularization_btn_2.setCheckable(True)
        self.regularization_btn_2.setAutoExclusive(True)
        self.regularization_btn_2.setObjectName("regularization_btn_2")
        self.verticalLayout_2.addWidget(self.regularization_btn_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 367, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.sign_out_btn_2 = QtWidgets.QPushButton(parent=self.icon_name_widget)
        self.sign_out_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.sign_out_btn_2.setIcon(icon2)
        self.sign_out_btn_2.setCheckable(True)
        self.sign_out_btn_2.setObjectName("sign_out_btn_2")
        self.verticalLayout_2.addWidget(self.sign_out_btn_2)
        self.gridLayout.addWidget(self.icon_name_widget, 0, 1, 1, 1)
        self.main_menu = QtWidgets.QWidget(parent=self.centralwidget)
        self.main_menu.setObjectName("main_menu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.main_menu)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.header_widget = QtWidgets.QWidget(parent=self.main_menu)
        self.header_widget.setObjectName("header_widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.header_widget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.menu_btn = QtWidgets.QPushButton(parent=self.header_widget)
        self.menu_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.menu_btn.setStyleSheet("border:none")
        self.menu_btn.setText("")
        icon3 = QtGui.QIcon()
        # icon3.addPixmap(QtGui.QPixmap(":/icons/menu.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon3.addPixmap(QtGui.QPixmap(self.resource_path("assets/icons/menu.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.menu_btn.setIcon(icon3)
        self.menu_btn.setIconSize(QtCore.QSize(20, 20))
        self.menu_btn.setCheckable(True)
        self.menu_btn.setObjectName("menu_btn")
        self.horizontalLayout_4.addWidget(self.menu_btn)
        spacerItem2 = QtWidgets.QSpacerItem(264, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.search_le = QtWidgets.QLineEdit(parent=self.header_widget)
        self.search_le.setObjectName("search_le")
        self.horizontalLayout.addWidget(self.search_le)
        self.search_btn = QtWidgets.QPushButton(parent=self.header_widget)
        self.search_btn.setStyleSheet("border:none\n"
"")
        self.search_btn.setText("")
        icon4 = QtGui.QIcon()
        # icon4.addPixmap(QtGui.QPixmap(":/icons/search.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        
        icon4.addPixmap(QtGui.QPixmap(self.resource_path("icons/search.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.search_btn.setIcon(icon4)
        self.search_btn.setCheckable(True)
        self.search_btn.setObjectName("search_btn")
        self.horizontalLayout.addWidget(self.search_btn)
        self.horizontalLayout_4.addLayout(self.horizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(264, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.profile_btn = QtWidgets.QPushButton(parent=self.header_widget)
        self.profile_btn.setStyleSheet("border:none")
        self.profile_btn.setText("")
        icon5 = QtGui.QIcon()
        # icon5.addPixmap(QtGui.QPixmap(":/icons/image (1).png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon5.addPixmap(QtGui.QPixmap(self.resource_path("assets/icons/image (1).png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.profile_btn.setIcon(icon5)
        self.profile_btn.setObjectName("profile_btn")
        self.horizontalLayout_4.addWidget(self.profile_btn)
        self.verticalLayout_3.addWidget(self.header_widget)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.main_menu)
        self.stackedWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.project_page = QtWidgets.QWidget()
        self.project_page.setStyleSheet("QComboBox{\n"
"border:1px solid #ccc;\n"
"padding:4px;\n"
"border-radius: 2px;\n"
"\n"
"\n"
"}\n"
"QComboBox:focus{\n"
"\n"
" border: 1px solid #0078d4;\n"
"            background-color: #fff;\n"
"\n"
"}\n"
"")
        self.project_page.setObjectName("project_page")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.project_page)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.project_page)
        self.scrollArea.setStyleSheet("timesheet_widget{\n"
"\n"
"background-color: #ffffff;\n"
"border: 1px solid #e0e0e0;\n"
"border-radius: 10px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 957, 618))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.timesheet_widget = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents)
        self.timesheet_widget.setObjectName("timesheet_widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.timesheet_widget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(parent=self.timesheet_widget)
        self.label_4.setMinimumSize(QtCore.QSize(150, 0))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.week_combo = QtWidgets.QComboBox(parent=self.timesheet_widget)
        self.week_combo.setMinimumSize(QtCore.QSize(150, 0))
        self.week_combo.setObjectName("week_combo")
        self.horizontalLayout_5.addWidget(self.week_combo)
        spacerItem4 = QtWidgets.QSpacerItem(338, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.btn_sign_in_sign_out = QtWidgets.QPushButton(parent=self.timesheet_widget)
        self.btn_sign_in_sign_out.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_sign_in_sign_out.setStyleSheet("QPushButton{\n"
"border:none;\n"
"border-radius:4px;\n"
"padding:6px;\n"
"padding-left-10px;\n"
"padding-right:10px;\n"
"background-color: rgb(31, 149, 239);\n"
"color:white;\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#1668a7;\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"}")
        self.btn_sign_in_sign_out.setObjectName("btn_sign_in_sign_out")
        self.horizontalLayout_5.addWidget(self.btn_sign_in_sign_out)
        self.logs_btn = QtWidgets.QPushButton(parent=self.timesheet_widget)
        self.logs_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.logs_btn.setStyleSheet("QPushButton{\n"
"border:none;\n"
"border-radius:4px;\n"
"padding:6px;\n"
"padding-left-10px;\n"
"padding-right:10px;\n"
"background-color: rgb(31, 149, 239);\n"
"color:white;\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#1668a7;\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"}")
        self.logs_btn.setObjectName("logs_btn")
        self.horizontalLayout_5.addWidget(self.logs_btn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(parent=self.timesheet_widget)
        self.label_5.setMinimumSize(QtCore.QSize(150, 0))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.project_combo = QtWidgets.QComboBox(parent=self.timesheet_widget)
        self.project_combo.setMinimumSize(QtCore.QSize(150, 0))
        self.project_combo.setObjectName("project_combo")
        self.horizontalLayout_6.addWidget(self.project_combo)
        self.label_22 = QtWidgets.QLabel(parent=self.timesheet_widget)
        self.label_22.setMinimumSize(QtCore.QSize(100, 0))
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_6.addWidget(self.label_22)
        self.subtask_combo = QtWidgets.QComboBox(parent=self.timesheet_widget)
        self.subtask_combo.setMinimumSize(QtCore.QSize(150, 0))
        self.subtask_combo.setObjectName("subtask_combo")
        self.horizontalLayout_6.addWidget(self.subtask_combo)
        spacerItem5 = QtWidgets.QSpacerItem(338, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.btn_refresh = QtWidgets.QPushButton(parent=self.timesheet_widget)
        self.btn_refresh.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_refresh.setMaximumSize(QtCore.QSize(16, 16))
        self.btn_refresh.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_refresh.setStyleSheet("border:none;")
        self.btn_refresh.setText("")
        icon6 = QtGui.QIcon()
        # icon6.addPixmap(QtGui.QPixmap(":/icons/refresh.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon6.addPixmap(QtGui.QPixmap(self.resource_path("assets/icons/refresh.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)

        self.btn_refresh.setIcon(icon6)
        self.btn_refresh.setObjectName("btn_refresh")
        self.horizontalLayout_6.addWidget(self.btn_refresh)
        self.btn_delete = QtWidgets.QPushButton(parent=self.timesheet_widget)
        self.btn_delete.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_delete.setMaximumSize(QtCore.QSize(16, 16))
        self.btn_delete.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_delete.setStyleSheet("border:none;")
        self.btn_delete.setText("")
        icon7 = QtGui.QIcon()
        # icon7.addPixmap(QtGui.QPixmap(":/icons/delete2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon7.addPixmap(QtGui.QPixmap(self.resource_path("assets/icons/delete2.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_delete.setIcon(icon7)
        self.btn_delete.setObjectName("btn_delete")
        self.horizontalLayout_6.addWidget(self.btn_delete)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.tableWidget = QtWidgets.QTableWidget(parent=self.timesheet_widget)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.DoubleClicked)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollMode.ScrollPerPixel)
        self.tableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollMode.ScrollPerItem)
        self.tableWidget.setShowGrid(False)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(32)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.verticalLayout_4.addWidget(self.tableWidget)
        self.verticalLayout_5.addWidget(self.timesheet_widget)
        self.total_time_widget = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents)
        self.total_time_widget.setStyleSheet("QWidget{\n"
"background-color: #ffffff;\n"
"border: 1px solid #e0e0e0;\n"
"border-radius: 10px;\n"
"}\n"
"QLabel {\n"
"                background-color: none; /* Ensure labels remain unaffected */\n"
"                border: none;\n"
"                color: #333333;\n"
"                font-weight: normal;\n"
"            }\n"
"")
        self.total_time_widget.setObjectName("total_time_widget")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.total_time_widget)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_6 = QtWidgets.QLabel(parent=self.total_time_widget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_14.addWidget(self.label_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.day1 = QtWidgets.QLabel(parent=self.total_time_widget)
        self.day1.setObjectName("day1")
        self.horizontalLayout_7.addWidget(self.day1)
        self.day1_value = QtWidgets.QLabel(parent=self.total_time_widget)
        self.day1_value.setObjectName("day1_value")
        self.horizontalLayout_7.addWidget(self.day1_value)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.day2 = QtWidgets.QLabel(parent=self.total_time_widget)
        self.day2.setObjectName("day2")
        self.horizontalLayout_9.addWidget(self.day2)
        self.day2_value = QtWidgets.QLabel(parent=self.total_time_widget)
        self.day2_value.setObjectName("day2_value")
        self.horizontalLayout_9.addWidget(self.day2_value)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.day3 = QtWidgets.QLabel(parent=self.total_time_widget)
        self.day3.setObjectName("day3")
        self.horizontalLayout_8.addWidget(self.day3)
        self.day3_value = QtWidgets.QLabel(parent=self.total_time_widget)
        self.day3_value.setObjectName("day3_value")
        self.horizontalLayout_8.addWidget(self.day3_value)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.day4 = QtWidgets.QLabel(parent=self.total_time_widget)
        self.day4.setObjectName("day4")
        self.horizontalLayout_10.addWidget(self.day4)
        self.day4_value = QtWidgets.QLabel(parent=self.total_time_widget)
        self.day4_value.setObjectName("day4_value")
        self.horizontalLayout_10.addWidget(self.day4_value)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.day5 = QtWidgets.QLabel(parent=self.total_time_widget)
        self.day5.setObjectName("day5")
        self.horizontalLayout_11.addWidget(self.day5)
        self.day5_value = QtWidgets.QLabel(parent=self.total_time_widget)
        self.day5_value.setObjectName("day5_value")
        self.horizontalLayout_11.addWidget(self.day5_value)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.day6 = QtWidgets.QLabel(parent=self.total_time_widget)
        self.day6.setObjectName("day6")
        self.horizontalLayout_12.addWidget(self.day6)
        self.day6_value = QtWidgets.QLabel(parent=self.total_time_widget)
        self.day6_value.setObjectName("day6_value")
        self.horizontalLayout_12.addWidget(self.day6_value)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.day7 = QtWidgets.QLabel(parent=self.total_time_widget)
        self.day7.setObjectName("day7")
        self.horizontalLayout_13.addWidget(self.day7)
        self.day7_value = QtWidgets.QLabel(parent=self.total_time_widget)
        self.day7_value.setObjectName("day7_value")
        self.horizontalLayout_13.addWidget(self.day7_value)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_13)
        self.total_time = QtWidgets.QLabel(parent=self.total_time_widget)
        self.total_time.setObjectName("total_time")
        self.horizontalLayout_14.addWidget(self.total_time)
        self.verticalLayout_5.addWidget(self.total_time_widget)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.btn_add_project = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.btn_add_project.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_add_project.setStyleSheet("QPushButton{\n"
"border:none;\n"
"border-radius:4px;\n"
"padding:6px;\n"
"padding-left-10px;\n"
"padding-right:10px;\n"
"background-color: rgb(31, 149, 239);\n"
"color:white;\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#1668a7;\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"}")
        self.btn_add_project.setCheckable(True)
        self.btn_add_project.setObjectName("btn_add_project")
        self.horizontalLayout_15.addWidget(self.btn_add_project)
        self.btn_save_calc = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.btn_save_calc.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_save_calc.setStyleSheet("QPushButton{\n"
"border:none;\n"
"border-radius:4px;\n"
"padding:6px;\n"
"padding-left-10px;\n"
"padding-right:10px;\n"
"background-color: rgb(31, 149, 239);\n"
"color:white;\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#1668a7;\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"}")
        self.btn_save_calc.setCheckable(True)
        self.btn_save_calc.setObjectName("btn_save_calc")
        self.horizontalLayout_15.addWidget(self.btn_save_calc)
        self.export_btn = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.export_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.export_btn.setStyleSheet("QPushButton{\n"
"border:none;\n"
"border-radius:4px;\n"
"padding:6px;\n"
"padding-left-10px;\n"
"padding-right:10px;\n"
"background-color: rgb(31, 149, 239);\n"
"color:white;\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#1668a7;\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"}")
        self.export_btn.setObjectName("export_btn")
        self.horizontalLayout_15.addWidget(self.export_btn)
        spacerItem6 = QtWidgets.QSpacerItem(678, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem6)
        self.verticalLayout_5.addLayout(self.horizontalLayout_15)
        self.gridLayout_2.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_3.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.project_page)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget.addWidget(self.page)
        self.regularization_page = QtWidgets.QWidget()
        self.regularization_page.setObjectName("regularization_page")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.regularization_page)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.widget = QtWidgets.QWidget(parent=self.regularization_page)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.calendarWidget = QtWidgets.QCalendarWidget(parent=self.widget)
        self.calendarWidget.setStyleSheet("")
        self.calendarWidget.setObjectName("calendarWidget")
        self.verticalLayout_6.addWidget(self.calendarWidget)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem7 = QtWidgets.QSpacerItem(798, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem7)
        self.pushButton = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton.setMinimumSize(QtCore.QSize(101, 35))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"border:none;\n"
"border-radius:4px;\n"
"padding:6px;\n"
"padding-left-10px;\n"
"padding-right:10px;\n"
"background-color: rgb(31, 149, 239);\n"
"color:white;\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#1668a7;\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_16.addWidget(self.pushButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_16)
        self.gridLayout_4.addWidget(self.widget, 0, 1, 1, 1)
        self.stackedWidget.addWidget(self.regularization_page)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        self.gridLayout.addWidget(self.main_menu, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.menu_btn.toggled['bool'].connect(self.icon_only_widget.setHidden) # type: ignore
        self.menu_btn.toggled['bool'].connect(self.icon_name_widget.setVisible) # type: ignore
        self.project_btn_1.toggled['bool'].connect(self.project_btn_2.setChecked) # type: ignore
        self.project_btn_2.toggled['bool'].connect(self.project_btn_1.setChecked) # type: ignore
        self.regularization_btn_2.toggled['bool'].connect(self.regularization_btn_1.setChecked) # type: ignore
        self.regularization_btn_1.toggled['bool'].connect(self.regularization_btn_2.setChecked) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def resource_path(self,relative_path):
        if getattr(sys, '_MEIPASS', False):
                base_path = sys._MEIPASS
                # print(f"Running in bundled mode. Base path: {base_path}")
        else:
                current_dir=os.path.dirname(os.path.abspath(__file__))
                # base_path = os.path.abspath(os.path.join(current_dir, "..",".."))
                project_root = os.path.abspath(os.path.join(current_dir, "..", ".."))
                base_path = os.path.join(project_root)
                
                # print(f"Running in source mode. Base pat: {base_path}")
        full_path = os.path.join(base_path, relative_path)
        # print(f"Resolved path for {relative_path}: {full_path}")
        return full_path
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Sidebar"))
        self.project_btn_2.setText(_translate("MainWindow", "Project"))
        self.regularization_btn_2.setText(_translate("MainWindow", "Regularisation"))
        self.sign_out_btn_2.setText(_translate("MainWindow", "Sign Out"))
        self.label_4.setText(_translate("MainWindow", "Week"))
        self.btn_sign_in_sign_out.setText(_translate("MainWindow", "Sign In"))
        self.logs_btn.setText(_translate("MainWindow", "My logs"))
        self.label_5.setText(_translate("MainWindow", "Select Project / Non-Billable"))
        self.label_22.setText(_translate("MainWindow", "Select Subtask"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Project Id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Segment"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Subtask"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Dec 01-Mon"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Dec 02-Tue"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Dec 03-Wed"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Dec 04-Thu"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Dec 05-Fri"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Dec 06-Sat"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Dec 07-Sun"))
        self.label_6.setText(_translate("MainWindow", "Total Hours:"))
        self.day1.setText(_translate("MainWindow", "Dec 01:"))
        self.day1_value.setText(_translate("MainWindow", "0"))
        self.day2.setText(_translate("MainWindow", "Dec 02:"))
        self.day2_value.setText(_translate("MainWindow", "0"))
        self.day3.setText(_translate("MainWindow", "Dec 03:"))
        self.day3_value.setText(_translate("MainWindow", "0"))
        self.day4.setText(_translate("MainWindow", "Dec 04:"))
        self.day4_value.setText(_translate("MainWindow", "0"))
        self.day5.setText(_translate("MainWindow", "Dec 05:"))
        self.day5_value.setText(_translate("MainWindow", "0"))
        self.day6.setText(_translate("MainWindow", "Dec 06:"))
        self.day6_value.setText(_translate("MainWindow", "0"))
        self.day7.setText(_translate("MainWindow", "Dec 07:"))
        self.day7_value.setText(_translate("MainWindow", "0"))
        self.total_time.setText(_translate("MainWindow", "0"))
        self.btn_add_project.setText(_translate("MainWindow", "Add Project"))
        self.btn_save_calc.setText(_translate("MainWindow", "Save and Calculate"))
        self.export_btn.setText(_translate("MainWindow", "Export"))
        self.pushButton.setText(_translate("MainWindow", "Regularize"))
