# Form implementation generated from reading ui file '..\ui\excel_report_user.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(410, 232)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(parent=Dialog)
        self.widget.setMinimumSize(QtCore.QSize(0, 0))
        self.widget.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.widget.setStyleSheet("QComboBox{\n"
"border:1px solid #ccc;\n"
"padding:6px;\n"
"border-radius: 2px;\n"
"\n"
"\n"
"}\n"
"QComboBox:focus{\n"
"\n"
" border: 1px solid #0078d4;\n"
"            background-color: #fff;\n"
"\n"
"}\n"
"QPushButton{\n"
"border:none;\n"
"border-radius:4px;\n"
"padding:6px;\n"
"padding-left-10px;\n"
"padding-right:10px;\n"
"background-color: rgb(31, 149, 239);\n"
"color:white;\n"
"padding:8px;\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#1668a7;\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"}")
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("\n"
"QLabel{\n"
"color:#000;\n"
"\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.month_or_week_com = QtWidgets.QComboBox(parent=self.widget)
        self.month_or_week_com.setObjectName("month_or_week_com")
        self.month_or_week_com.addItem("")
        self.month_or_week_com.addItem("")
        self.verticalLayout.addWidget(self.month_or_week_com)
        self.start_mon_week_combo = QtWidgets.QComboBox(parent=self.widget)
        self.start_mon_week_combo.setObjectName("start_mon_week_combo")
        self.start_mon_week_combo.addItem("")
        self.verticalLayout.addWidget(self.start_mon_week_combo)
        self.end_month_week_combo = QtWidgets.QComboBox(parent=self.widget)
        self.end_month_week_combo.setObjectName("end_month_week_combo")
        self.end_month_week_combo.addItem("")
        self.verticalLayout.addWidget(self.end_month_week_combo)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_extract = QtWidgets.QPushButton(parent=self.widget)
        self.btn_extract.setMinimumSize(QtCore.QSize(140, 0))
        self.btn_extract.setObjectName("btn_extract")
        self.horizontalLayout.addWidget(self.btn_extract)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Export To Excel"))
        self.month_or_week_com.setItemText(0, _translate("Dialog", "By Month"))
        self.month_or_week_com.setItemText(1, _translate("Dialog", "By Week"))
        self.start_mon_week_combo.setItemText(0, _translate("Dialog", "January"))
        self.end_month_week_combo.setItemText(0, _translate("Dialog", "December"))
        self.btn_extract.setText(_translate("Dialog", "Extract"))
