# Form implementation generated from reading ui file '..\ui\extract_log_user.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import sys,os

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(388, 203)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.main_widget = QtWidgets.QWidget(parent=Dialog)
        self.main_widget.setObjectName("main_widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.main_widget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.header_widget = QtWidgets.QWidget(parent=self.main_widget)
        self.header_widget.setStyleSheet("background-color: rgb(31, 149, 239);")
        self.header_widget.setObjectName("header_widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.header_widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(parent=self.header_widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:#fff;")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.verticalLayout_4.addWidget(self.header_widget)
        self.body_widget = QtWidgets.QWidget(parent=self.main_widget)
        self.body_widget.setStyleSheet("QLineEdit{\n"
"color: #666;\n"
"font-size: 14px;\n"
"padding: 4px;\n"
"border: 1px solid #ccc;\n"
"border-radius: 2px;\n"
"background-color: #f9f9f9;\n"
"}\n"
"QLineEdit:focus {\n"
"            border: 1px solid #0078d4;\n"
"            background-color: #fff;\n"
"        }\n"
"")
        self.body_widget.setObjectName("body_widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.body_widget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.body_widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label_2 = QtWidgets.QLabel(parent=self.body_widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(15)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.start_le = QtWidgets.QLineEdit(parent=self.body_widget)
        self.start_le.setObjectName("start_le")
        self.horizontalLayout.addWidget(self.start_le)
        self.btn_calender_1 = QtWidgets.QPushButton(parent=self.body_widget)
        self.btn_calender_1.setMinimumSize(QtCore.QSize(20, 20))
        self.btn_calender_1.setMaximumSize(QtCore.QSize(20, 20))
        self.btn_calender_1.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_calender_1.setStyleSheet("border:none;")
        self.btn_calender_1.setText("")
        icon = QtGui.QIcon()
        # icon.addPixmap(QtGui.QPixmap(":/icons/calender.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon.addPixmap(QtGui.QPixmap(self.resource_path("assets/icons/calender.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_calender_1.setIcon(icon)
        self.btn_calender_1.setIconSize(QtCore.QSize(20, 1620))
        self.btn_calender_1.setObjectName("btn_calender_1")
        self.horizontalLayout.addWidget(self.btn_calender_1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(15)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.end_le = QtWidgets.QLineEdit(parent=self.body_widget)
        self.end_le.setObjectName("end_le")
        self.horizontalLayout_2.addWidget(self.end_le)
        self.btn_calender_2 = QtWidgets.QPushButton(parent=self.body_widget)
        self.btn_calender_2.setMinimumSize(QtCore.QSize(20, 20))
        self.btn_calender_2.setMaximumSize(QtCore.QSize(20, 20))
        self.btn_calender_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_calender_2.setStyleSheet("border:none;")
        self.btn_calender_2.setText("")
        self.btn_calender_2.setIcon(icon)
        self.btn_calender_2.setIconSize(QtCore.QSize(20, 20))
        self.btn_calender_2.setObjectName("btn_calender_2")
        self.horizontalLayout_2.addWidget(self.btn_calender_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(parent=self.body_widget)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton{\n"
"border:none;\n"
"border-radius:4px;\n"
"padding:8px;\n"
"padding-left:24px;\n"
"padding-right:24px;\n"
"background-color: rgb(31, 149, 239);\n"
"color:white;\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#1668a7;\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.verticalLayout_5.setStretch(0, 1)
        self.verticalLayout_4.addWidget(self.body_widget)
        self.verticalLayout_4.setStretch(1, 1)
        self.gridLayout.addWidget(self.main_widget, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)


    def resource_path(self,relative_path):
        if getattr(sys, '_MEIPASS', False):
                base_path = sys._MEIPASS
                # print(f"Running in bundled mode. Base path: {base_path}")
        else:
                current_dir=os.path.dirname(os.path.abspath(__file__))
                # base_path = os.path.abspath(os.path.join(current_dir, "..",".."))
                project_root = os.path.abspath(os.path.join(current_dir, "..", ".."))
                base_path = os.path.join(project_root)
                
                # print(f"Running in source mode. Base pat: {base_path}")
        full_path = os.path.join(base_path, relative_path)
        # print(f"Resolved path for {relative_path}: {full_path}")
        return full_path
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setText(_translate("Dialog", "Extract your logs"))
        self.label.setText(_translate("Dialog", "From "))
        self.label_2.setText(_translate("Dialog", "To"))
        self.pushButton.setText(_translate("Dialog", "Extract"))
