# Form implementation generated from reading ui file '..\ui\reset_user_password.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(406, 224)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(parent=Dialog)
        self.widget.setStyleSheet("QComboBox{\n"
"border:1px solid #ccc;\n"
"padding:4px;\n"
"border-radius: 2px;\n"
"\n"
"\n"
"}\n"
"QComboBox:focus{\n"
"\n"
" border: 1px solid #0078d4;\n"
"            background-color: #fff;\n"
"\n"
"}\n"
"\n"
"QLineEdit{\n"
"color: #666;\n"
"font-size: 14px;\n"
"padding: 4px;\n"
"border: 1px solid #ccc;\n"
"border-radius: 2px;\n"
"background-color: #f9f9f9;\n"
"}\n"
"QLineEdit:focus {\n"
"            border: 1px solid #0078d4;\n"
"            background-color: #fff;\n"
"        }\n"
"QPushButton{\n"
"border:none;\n"
"border-radius:4px;\n"
"padding:7px;\n"
"padding-left-10px;\n"
"padding-right:10px;\n"
"background-color: rgb(31, 149, 239);\n"
"color:white;\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#1668a7;\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"}")
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.employee_combo = QtWidgets.QComboBox(parent=self.widget)
        self.employee_combo.setObjectName("employee_combo")
        self.verticalLayout.addWidget(self.employee_combo)
        self.new_pass_le = QtWidgets.QLineEdit(parent=self.widget)
        self.new_pass_le.setObjectName("new_pass_le")
        self.verticalLayout.addWidget(self.new_pass_le)
        self.confirm_new_pass_le = QtWidgets.QLineEdit(parent=self.widget)
        self.confirm_new_pass_le.setObjectName("confirm_new_pass_le")
        self.verticalLayout.addWidget(self.confirm_new_pass_le)
        self.reset_pass_btn = QtWidgets.QPushButton(parent=self.widget)
        self.reset_pass_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.reset_pass_btn.setStyleSheet("padding:6px;")
        self.reset_pass_btn.setObjectName("reset_pass_btn")
        self.verticalLayout.addWidget(self.reset_pass_btn)
        self.gridLayout_2.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.widget, 0, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Reset User Password"))
        self.new_pass_le.setPlaceholderText(_translate("Dialog", "New Password"))
        self.confirm_new_pass_le.setPlaceholderText(_translate("Dialog", "Confirm New Password"))
        self.reset_pass_btn.setText(_translate("Dialog", "Reset Password"))
